name: Terraform

on:
  push:
    branches:
    - main
    paths:
    - '**.tf'
    - '**.tfvars'
  pull_request:
    branches:
    - main
    paths:
    - '**.tf'
    - '**.tfvars'
  workflow_dispatch:

jobs:
  terraform:
    uses: ./.github/workflows/terraform-reusable.yaml
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}